Fix CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -86,8 +86,9 @@ jobs:
               fi
 
               if [[ $(git diff $COMMIT_RANGE --name-status | grep "$orbname") ]]; then
-                (ls ${DIST_DIR}/${ORB}orb.yml && echo "orb.yml found, attempting to publish...") || echo "No orb.yml file was found - the next line is expected to fail."
-                circleci orb publish ${DIST_DIR}/${ORB}orb.yml sugarshin/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
+                orbfile=${DIST_DIR}/${orbname}/orb.yml
+                (ls ${orbfile} && echo "orb.yml found, attempting to publish...") || echo "No orb.yml file was found - the next line is expected to fail."
+                circleci orb publish ${orbfile} sugarshin/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
               else
                 echo "${orbname} not modified; no need to promote"
               fi
